### ISSUE TITLE
ServerDisconnectedError - add possibility to tweak keep-alive setting

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/python-tahoma-api#27]
Initially reported in https://github.com/iMicknl/ha-tahoma/issues/191. ServerDisconnectedError can be faced when we open to many requests. 

>Try setting the client to tell the server to close the connection after each request:

>   self._session = aiohttp.ClientSession(
        ...
        headers={"Connection": "close"},
>     )

>HTTP keep-alive allows the same connection to be used for multiple requests, which can improve performance, especially over HTTPS, where the connection handshake can be lengthy. But the server may have a limit as to how long it's willing to keep the connection alive or how many requests it will accept on the same connection. When the limit runs out, it closes the connection.

_Originally posted by @rogerdahl in https://github.com/aio-libs/aiohttp/issues/850#issuecomment-471663047_

**Comment by tetienne** [comment]
As discussed in the issue you linked, we don't need to change this header. Increasing the poll interval from 5 to 10 seconds has been enough. Closing the session at each request is something we can avoid.

**Comment by iMicknl** [comment]
@tetienne that is the behavior in our HA integration. However, I can understand that there certainly are scenarios where you want to poll more often. Especially since polling every second is allowed by Somfy TaHoma servers...

**Comment by tetienne** [comment]
@iMicknl On the Tahomalink website, the Connection header is set to keep-alive.

**Comment by thijsdejong** [comment]
On the Tahomalink website the Keep-Alive header in the response has the following values `Keep-Alive: timeout=5, max=37`. The second value decreases with each additional request. As soon as the max value is 1, the next request is different. Instead of responding with `Connection: Keep-Alive`, the server responds with `Connection: close`.

I'm wondering if this behaviour is handled by aiohttp, I could not find anything on it.
